---
title: "Supplemental Tables"
format:
    pdf:
        mainfont: "Arial"
        lot: true
        fig-align: center
        fig-width: 8.5
        fig-height: 11
        documentclass: article
        geometry: margin=0.25in
        output-file: "Supplemental_Tables.pdf"
include-before-body:
    - text: |
        \captionsetup{justification=raggedright,singlelinecheck=false}
crossref:
    tbl-title: "**Supplemental Table**"
    tbl-labels: "**arabic**"
    title-delim: "**.**"

---

\newpage

```{r setup}
# load packages
library(knitr)
library(writexl)
library(GAMBLR.open)
library(tidyverse)
```

```{r tbl1}
#| label: tbl-sup1
#| tbl-cap: "Preview of sample metadata."


metadata <- get_gambl_metadata() %>%
    dplyr::filter(study == "FL_Dreval")

kable(
    metadata %>%
        select(1:5) %>%
        head()
)
```

```{r tbl2}
#| label: tbl-sup2
#| tbl-cap: "Preview of somatic mutations."

maf <- get_ssm_by_samples(
    these_samples_metadata = metadata,
    tool_name = "publication"
)

kable(
    maf %>%
        select(1:7) %>%
        head()
)
```


```{r export_stables}
sheets <- list(
    "S1. Sample metadata" = colnames_to_column(
        metadata,
        title = "Supplemental Table 1. Metadata of samples used in this study."
    ),
    "S2. SSM" = colnames_to_column(
        maf,
        title = "Supplemental Table 2. Simple somatic mutations in the maf format."
    )
)

write_xlsx(
    sheets,
    "Supplemental_Tables.xlsx",
    col_names = FALSE
)
```
